POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "cocinero@queen.com",
    "password": "123456"
}

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "email": "cocinero@queen.com",
    "password": "123456",
    "role":"chef"
}

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY2luZXJvQHF1ZWVuLmNvbSIsImlhdCI6MTY5MjQ4NzExNSwiZXhwIjoxNjkyNDkwNzE1LCJzdWIiOiI3In0.bT5WwdBrxj7GjyvZRA9zNB3RPIgiHr_KCFlhCa8yOpE

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY2luZXJvQHF1ZWVuLmNvbSIsImlhdCI6MTY5MjIxODU3OSwiZXhwIjoxNjkyMjIyMTc5LCJzdWIiOiI3In0.06VBqOyxuW5_2yaBK7dWz82rHVoojCzTxDY9v1x-JTw

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5MjAyOTQ0MSwiZXhwIjoxNjkyMDMzMDQxLCJzdWIiOiIyIn0.-995mt1vRvzWH7l7SNeTZY_oEiUkuG03DWWtS7Z4cds

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzNDAzNSwiZXhwIjoxNjUwMjM3NjM1LCJzdWIiOiIyIn0.q6lDwW_wyK6-8-lUyiLUwnoowRLsvuFblu1yufkaa_Q

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}

DELETE http://localhost:8080/orders/24 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5MjAyOTQ0MSwiZXhwIjoxNjkyMDMzMDQxLCJzdWIiOiIyIn0.-995mt1vRvzWH7l7SNeTZY_oEiUkuG03DWWtS7Z4cds

POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5MTUzMzE5OCwiZXhwIjoxNjkxNTM2Nzk4LCJzdWIiOiIyIn0.MHULlldb_zKaPGSSQjohSQnfc8vElP7BqV0Sz03R3DU

{
    "client": "pao",
    "products": [
        {
            "qty": 1,
            "product": {
            "id": 1,
            "name": "Sandwich de jamón y queso",
            "price": 1000,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/sandwich.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        },
        {
            "qty": 1,
            "product": {
            "id": 2,
            "name": "Café americano",
            "price": 500,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/coffe.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        }
    ],
    "status": "pending",
    "dataEntry": "2022-03-05 15:00"
}